In [1]:
import yfinance as yf
prices = yf.download(tickers = symbols,period = "1d",interval = "1d",group_by = 'column',auto_adjust = True,prepost = False,threads = True)
start, end = md.getNDateAndToday(ndays)
dfDaysAgo = yf.download(tickers = symbols,interval = "1d",start=start,end=end,group_by = 'column',auto_adjust = True,prepost = False,threads = True)

data = yf.download(  # or pdr.get_data_yahoo(...
        # tickers list or string as well
        tickers = "SPY QQQ",

        # use "period" instead of start/end
        # valid periods: 1d,5d,1mo,3mo,6mo,1y,2y,5y,10y,ytd,max
        # (optional, default is '1mo')
        period = "1d",

        # fetch data by interval (including intraday if period < 60 days)
        # valid intervals: 1m,2m,5m,15m,30m,60m,90m,1h,1d,5d,1wk,1mo,3mo
        # (optional, default is '1d')
        interval = "1d",

        # group by ticker (to access via data['SPY'])
        # (optional, default is 'column')
        group_by = 'column',

        # adjust all OHLC automatically
        # (optional, default is False)
        auto_adjust = True,

        # download pre/post regular market hours data
        # (optional, default is False)
        prepost = True,

        # use threads for mass downloading? (True/False/Integer)
        # (optional, default is True)
        threads = True,

        # proxy URL scheme use use when downloading?
        # (optional, default is None)
        proxy = None

)
data

[*********************100%***********************]  2 of 2 completed

                 Close                    High                     Low  \
                   QQQ         SPY         QQQ         SPY         QQQ
Date
2021-01-15  311.859985  375.700012  315.119995  377.579987  310.579987
2021-01-15  311.859985  375.700012  315.119995  377.579987  310.591095

                              Open                Volume
                   SPY         QQQ         SPY       QQQ        SPY
Date
2021-01-15  373.700012  314.130005  376.720001  34797700  107046400
2021-01-15  373.700012  314.130005  376.720001  35118718  107159962

In [3]:
data['Close']

                   QQQ         SPY
Date
2020-09-04  283.579987  342.350006