In [9]:
import yfinance as yf
ticker = 'AMZN'
stock_data = yf.Ticker(ticker)
stock_data.options

('2020-02-06',
 '2020-02-13',
 '2020-02-20',
 '2020-02-27',
 '2020-03-05',
 '2020-03-12',
 '2020-03-19',
 '2020-04-16',
 '2020-06-18',
 '2020-07-16',
 '2020-09-17',
 '2021-01-14',
 '2021-06-17',
 '2022-01-20')

In [22]:

# get option chain for specific expiration
option_data = stock_data.option_chain(msft.options[0])
# data available via: opt.calls, opt.puts
print(option_data[0].iloc[0:2])

        contractSymbol  lastTradeDate  strike  lastPrice     bid     ask  \
0  AMZN200207C01000000     1580496608  1000.0    1025.15  1004.8  1012.0
1  AMZN200207C01020000     1580417050  1020.0    1007.80   984.8   992.0

      change  percentChange  volume  openInterest  impliedVolatility  \
0  153.80005      17.650778    10.0           NaN           2.428837
1  155.84998      18.293324     NaN           NaN           2.366459

   inTheMoney contractSize currency
0        True      REGULAR      USD
1        True      REGULAR      USD

In [26]:
df =option_data.calls
df1 = df[df.loc[:,'volume'] > 1000][['strike', 'volume', 'ask',  'bid', 'percentChange',   'lastPrice', 'inTheMoney']]
#lastTradeDate	strike	lastPrice	bid	ask	change	percentChange	volume	openInterest	impliedVolatility	inTheMoney	contractSize	currency
df1.sort_values(by=['strike'], ascending=False)

     strike  volume    ask    bid  percentChange  lastPrice  inTheMoney
193  2200.0  1597.0   1.50   1.00      42.857147       1.00       False
183  2150.0  1508.0   2.19   2.09      53.146862       2.19       False
177  2120.0  1381.0   4.00   3.25     102.020200       4.00       False
170  2100.0  6383.0   5.95   5.80     132.000000       5.80       False
158  2070.0  1060.0  11.90  10.50     256.666660      10.70       False
154  2060.0  1246.0  14.00  13.00     271.584720      13.60       False
150  2050.0  3463.0  16.45  16.20     285.714320      16.20       False
148  2045.0  1706.0  18.80  17.15     373.750030      18.95       False
146  2040.0  2559.0  20.50  19.15     295.000000      19.75       False
142  2030.0  2931.0  24.00  22.55     367.999970      23.40       False
140  2025.0  1727.0  26.40  24.60     264.285700      25.50       False
138  2020.0  1364.0  28.60  27.00     592.753660      28.68       False
130  2000.0  3576.0  38.80  36.60     419.178100      37.90        True